INSERT INTO categories (title, description, created_at) VALUES
    ('Web Development', 'Articles about building modern websites, backend systems, frontend interfaces, and practical programming techniques.', '2026-04-01 09:00:00'),
    ('Hosting & Servers', 'Guides and tips about web hosting, server configuration, deployment, domains, SSL, and performance optimization.', '2026-04-02 09:15:00'),
    ('Cybersecurity', 'Posts about website security, common vulnerabilities, secure coding practices, and protecting online projects.', '2026-04-03 09:30:00'),
    ('Business & Technology', 'Articles about digital tools, online business, automation, productivity, and how technology supports company growth.', '2026-04-04 09:45:00'),
    ('Tutorials', 'Step-by-step practical guides for developers, website owners, and beginners who want to learn technical topics clearly.', '2026-04-05 10:00:00');

INSERT INTO articles (image, title, description, content, view_count, published_at, created_at) VALUES
    ('web-development-basics.jpg', 'Getting Started with Modern Web Development', 'A beginner-friendly overview of how modern websites are built.', 'Modern web development usually includes frontend code, backend logic, databases, hosting, and deployment. Understanding how these parts work together helps developers build reliable and maintainable websites.', 128, '2026-05-01 10:00:00', '2026-04-18 08:20:00'),
    ('php-clean-structure.jpg', 'How to Structure a Pure PHP Project', 'Practical advice for organizing a PHP project without a framework.', 'A clean PHP project should separate public files, application logic, configuration, templates, and database code. This makes the code easier to understand, test, and extend.', 94, '2026-05-02 11:30:00', '2026-04-19 09:10:00'),
    ('smarty-template-engine.jpg', 'Using Smarty for PHP Templates', 'An introduction to separating PHP logic from HTML templates with Smarty.', 'Smarty allows developers to keep presentation logic separate from application logic. It is useful for rendering pages while keeping controllers and repositories focused on data handling.', 76, '2026-05-03 09:15:00', '2026-04-20 10:05:00'),
    ('mysql-blog-schema.jpg', 'Designing a MySQL Schema for a Blog', 'How categories, articles, and pivot tables work in a blog database.', 'A blog database usually contains articles, categories, and a relation table that connects them. This allows each article to belong to one or multiple categories.', 143, '2026-05-04 14:20:00', '2026-04-21 11:25:00'),
    ('docker-local-dev.jpg', 'Why Use Docker for Local Development', 'A simple explanation of how Docker helps developers run projects consistently.', 'Docker makes it easier to run PHP, MySQL, Nginx, and other services in isolated containers. This reduces environment differences between developers and servers.', 201, '2026-05-05 16:45:00', '2026-04-22 13:40:00'),
    ('nginx-php-fpm.jpg', 'Understanding Nginx and PHP-FPM', 'How Nginx and PHP-FPM work together in a PHP application.', 'Nginx handles HTTP requests and static files, while PHP-FPM processes PHP scripts. Together they provide a common and efficient setup for PHP websites.', 167, '2026-05-06 08:40:00', '2026-04-23 14:55:00'),
    ('website-security.jpg', 'Basic Security Rules for PHP Websites', 'Essential security practices every PHP developer should know.', 'PHP applications should validate input, escape output, use prepared statements, protect secrets, and handle errors carefully. These habits reduce the risk of common vulnerabilities.', 230, '2026-05-07 13:10:00', '2026-04-24 15:35:00'),
    ('sql-injection.jpg', 'How Prepared Statements Prevent SQL Injection', 'A practical explanation of why prepared statements matter.', 'SQL injection happens when user input is incorrectly inserted into SQL queries. Prepared statements separate SQL logic from user data and help protect the database.', 188, '2026-05-08 12:00:00', '2026-04-25 16:15:00'),
    ('website-performance.jpg', 'Improving Website Performance with Simple Techniques', 'Small optimizations that can make a website faster.', 'Performance can be improved by optimizing database queries, compressing images, caching data, reducing unnecessary code, and loading only required assets.', 119, '2026-05-09 15:25:00', '2026-04-26 17:05:00'),
    ('business-automation.jpg', 'How Automation Helps Online Businesses', 'Examples of how technology can reduce manual work.', 'Automation helps businesses save time by handling repetitive tasks such as emails, reports, invoices, notifications, and data synchronization.', 87, '2026-05-10 10:50:00', '2026-04-27 09:50:00'),
    ('developer-productivity.jpg', 'Useful Habits for Developer Productivity', 'Simple habits that help developers work more effectively.', 'Good developers write readable code, commit progressively, document important decisions, test critical logic, and keep project structure simple.', 156, '2026-05-11 09:30:00', '2026-04-28 10:30:00'),
    ('deployment-checklist.jpg', 'Simple Website Deployment Checklist', 'A checklist for preparing a PHP website for deployment.', 'Before deploying a website, check environment variables, database credentials, file permissions, error reporting, SSL configuration, and backup strategy.', 132, '2026-05-12 17:00:00', '2026-04-29 11:45:00'),
    ('web-development-basics.jpg', 'Choosing the Right PHP Project Structure', 'How to decide where controllers, repositories, and templates belong.', 'A small PHP application stays maintainable when public entrypoints, application code, database access, and templates have clear responsibilities. The structure should be simple enough to understand but strict enough to prevent files from becoming tangled.', 104, '2026-05-13 09:20:00', '2026-04-30 08:10:00'),
    ('smarty-template-engine.jpg', 'Reusable Template Partials in Smarty', 'How partial templates keep repeated markup manageable.', 'Smarty partials are useful for repeated interface pieces such as article cards, pagination, headers, and footers. They help keep page templates readable while allowing shared markup to evolve in one place.', 91, '2026-05-14 10:40:00', '2026-05-01 09:25:00'),
    ('mysql-blog-schema.jpg', 'Indexes That Help Blog Category Pages', 'Practical indexing ideas for category lists and article sorting.', 'Category pages usually filter by category and sort by dates or view counts. Adding indexes around relation tables and sorted columns can keep these pages responsive as the number of posts grows.', 118, '2026-05-15 12:15:00', '2026-05-02 10:45:00'),
    ('docker-local-dev.jpg', 'Keeping Docker Development Predictable', 'Simple rules for reliable local containers.', 'A predictable Docker setup keeps service names, ports, mounted volumes, and environment variables consistent. This makes it easier to onboard another developer and reproduce the application locally.', 85, '2026-05-16 14:10:00', '2026-05-03 11:20:00'),
    ('nginx-php-fpm.jpg', 'Serving Static Assets with Nginx', 'How Nginx root paths affect images, CSS, and JavaScript.', 'Nginx serves static assets directly from the configured document root. If Docker volume mounts and root paths do not match, images and stylesheets may return 404 even when files exist in the repository.', 147, '2026-05-17 08:55:00', '2026-05-04 12:30:00'),
    ('website-security.jpg', 'Escaping Output in PHP Templates', 'Why template escaping matters for user-facing content.', 'Escaping output prevents stored content from becoming executable markup in the browser. Even simple blog projects should escape titles, descriptions, and dynamic links before rendering them.', 211, '2026-05-18 16:05:00', '2026-05-05 13:35:00'),
    ('sql-injection.jpg', 'Binding Integers in PDO Queries', 'Using bound integer parameters for limits, offsets, and IDs.', 'Prepared statements protect values from being interpreted as SQL. For numeric values such as IDs, limits, and offsets, binding with the integer parameter type makes intent explicit.', 173, '2026-05-19 09:45:00', '2026-05-06 14:20:00'),
    ('website-performance.jpg', 'Avoiding N Plus One Queries on Homepages', 'How grouped queries can reduce database round trips.', 'A homepage that shows posts for many categories can accidentally execute one query per category. Window functions or grouped queries can fetch the same data with fewer database round trips.', 98, '2026-05-20 11:10:00', '2026-05-07 15:15:00'),
    ('business-automation.jpg', 'Automation Ideas for Small Web Teams', 'Simple automation that reduces repetitive development work.', 'Small teams can benefit from automated setup scripts, seed data, linting, deployment checklists, and repeatable test commands. These practices reduce manual mistakes and save time.', 74, '2026-05-13 16:30:00', '2026-05-08 09:05:00'),
    ('developer-productivity.jpg', 'Debugging PHP Applications Methodically', 'A practical debugging flow for small PHP projects.', 'Effective debugging starts with reproducing the issue, isolating the failing layer, checking inputs and outputs, and removing temporary dumps before finishing the task.', 162, '2026-05-14 13:25:00', '2026-05-09 10:15:00'),
    ('deployment-checklist.jpg', 'Preparing Environment Files for Deployment', 'What to include and exclude in environment configuration.', 'Environment files should describe required variables without committing secrets. A clean example file helps reviewers and teammates configure the application quickly.', 126, '2026-05-15 15:40:00', '2026-05-10 11:35:00'),
    ('web-development-basics.jpg', 'Controller Responsibilities in Pure PHP', 'How controllers should coordinate requests without doing too much.', 'Controllers should read request data, call repositories or services, handle missing resources, and pass prepared data to templates. They should not contain SQL or presentation markup.', 109, '2026-05-16 08:35:00', '2026-05-11 12:50:00'),
    ('php-clean-structure.jpg', 'When to Add a Service Class', 'How to avoid unnecessary service layers while keeping code clean.', 'A service class is useful when logic is reused, complex, or does not belong naturally in a controller or repository. For small one-off behavior, a direct method call is often clearer.', 93, '2026-05-16 12:05:00', '2026-05-12 14:05:00'),
    ('smarty-template-engine.jpg', 'Template Layouts for PHP Blogs', 'Using layouts to share HTML structure across pages.', 'A shared layout keeps document structure, header, footer, and stylesheet links consistent. Page templates can then focus on their own content blocks.', 81, '2026-05-17 09:55:00', '2026-05-13 15:25:00'),
    ('mysql-blog-schema.jpg', 'Counting Articles for Pagination', 'How count queries support reliable pagination controls.', 'Pagination needs both a limited list query and a count query. The count tells the application how many pages exist and helps avoid empty pages for large page numbers.', 137, '2026-05-17 16:30:00', '2026-05-14 16:40:00'),
    ('website-security.jpg', 'Handling Missing Pages Clearly', 'Why 404 behavior matters in small applications.', 'A clear not found response helps users and search engines understand missing resources. Controllers should handle invalid IDs and missing database records intentionally.', 189, '2026-05-18 10:15:00', '2026-05-15 09:40:00'),
    ('website-performance.jpg', 'Keeping Article Images Lightweight', 'Why image size affects perceived website speed.', 'Large images can make otherwise simple pages feel slow. Choosing appropriate dimensions, compression, and caching headers improves the experience for readers.', 115, '2026-05-18 14:50:00', '2026-05-16 10:55:00'),
    ('deployment-checklist.jpg', 'Final Checks Before Sharing a Test Assignment', 'A checklist for reviewing a small project before submission.', 'Before submitting a test assignment, verify setup instructions, route behavior, seed data, database schema, static assets, and visible error output. A short final pass catches many avoidable issues.', 144, '2026-05-19 17:20:00', '2026-05-17 12:10:00');

INSERT INTO article_category (article_id, category_id) VALUES
    (1, 1),
    (1, 5),
    (2, 1),
    (2, 5),
    (3, 1),
    (3, 5),
    (4, 1),
    (4, 2),
    (5, 2),
    (5, 5),
    (6, 2),
    (7, 3),
    (7, 1),
    (8, 3),
    (8, 5),
    (9, 2),
    (9, 4),
    (10, 4),
    (11, 4),
    (11, 1),
    (12, 2),
    (12, 5),
    (13, 1),
    (13, 5),
    (14, 1),
    (14, 5),
    (15, 1),
    (15, 2),
    (16, 2),
    (16, 5),
    (17, 2),
    (18, 3),
    (18, 1),
    (19, 3),
    (19, 5),
    (20, 2),
    (20, 4),
    (21, 4),
    (22, 4),
    (22, 1),
    (23, 2),
    (23, 5),
    (24, 1),
    (25, 1),
    (25, 5),
    (26, 1),
    (26, 5),
    (27, 1),
    (27, 2),
    (28, 3),
    (28, 1),
    (29, 2),
    (29, 4),
    (30, 2),
    (30, 5);
